---
- name: Deployment configuration
  hosts: servers
  gather_facts: False
  vars_files:
      - ${TARGET}.yaml

  tasks:
    - name: Manually create the initial virtualenv
      command: virtualenv -p python3.6 ${HOME}/venvs/{% verbatim %}{{project_venv_name}} creates="${HOME}/venvs/{{project_venv_name}}{% endverbatim %}"
      tags: init
    - name: Clone repository
      git:{% verbatim %}
        repo={{git_repository}}
        dest=www/{{project_dir_name}}
        accept_hostkey=yes
        version={{branch}}
    - name: Install requirements
      pip:
        requirements=${HOME}/www/{{project_dir_name}}/requirements/prod.txt
        virtualenv=${HOME}/venvs/{{project_venv_name}}
    - name: Create vassall
      file:
        src: "${HOME}/www/{{project_dir_name}}/uwsgiconf/remotes/{{branch}}.ini"
        dest: "${HOME}/vassals/{{project_dir_name}}.ini"
        state: link
    - name: Create database
      postgresql_db:
        name={{project_dir_name}}
        encoding=UTF-8
        template=template0
        login_user={{db_user}}
        login_password={{db_password}}
      vars:
        ansible_python_interpreter: venvs/{{project_venv_name}}/bin/python
    - name: Migrate database
      command: "${HOME}/venvs/{{project_venv_name}}/bin/python manage.py migrate{% endverbatim %} --settings={{project_name}}.settings.{% verbatim %}{{settings}}"
      args:
        chdir: ${HOME}/www/{{project_dir_name}}/
    - name: Restart vassal
      file:
        path: "${HOME}/www/{{project_dir_name}}/uwsgiconf/remotes/{{settings}}.ini"
        state: touch{% endverbatim %}
